### ISSUE TITLE
Sensor not working at all

### ISSUE THREAD

**Issue by kemendib** [amaximus/met_alerts_hu#1]
Logger: homeassistant.components.sensor
Source: custom_components/met_alerts_hu/sensor.py:84
Integration: Érzékelő (documentation, issues)
First occurred: 6:49:50 (1 occurrences)
Last logged: 6:49:50

met_alerts_hu: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/config/custom_components/met_alerts_hu/sensor.py", line 145, in async_update
    mdata = await async_get_mdata(self)
  File "/config/custom_components/met_alerts_hu/sensor.py", line 84, in async_get_mdata
    a_lvl = m.group(0).replace('w','').replace('.gif','')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by amaximus** [comment]
Can you please provide your sensor config (especially county_id and region_id) to be able to reproduce the bug? Thanks.

**Comment by amaximus** [comment]
Issue has been fixed in recent version 1.0.3.

Please check on your side too and get back to me with results.

**Comment by kemendib** [comment]
Szia!

Feltetelezem, Te is magyar vagy, ezert batorkodom itt magyarul irni. A
forumon angolul irtam, hogy ne csesszek ki a kulfoldiekkel. :D

Maga az entitas mukodik, de a lovelace kartya nem akar. Telepitettem azt a
custom button card-ot, amit hianyolt, de igy is vastag piros, ha
megprobalom barhogyan berakni a peldakent emlitett modon. Mivel Budapesten
lakom, az entitas regiojanak es a megyekodnak is az Altalatok leirt kodot
irtam be, maganal az entitasnal latom is szepen attributumkent, amit latnom
kell. Nem vagyok programozozseni, ezert nem tudtam rajonni, mi baj van a
lovelace kartyaval. Ha hazaerek, bemasolom, mit ir ki.

Elore is koszonok minden segitseget! Valamint koszonom a kitarto munkat a
fejlesztesben!

Udv:

Kemendi Balazs

Atticus Maximus ***@***.***> ezt írta (időpont: 2021. jún.
21., H 15:26):

**Comment by amaximus** [comment]
Ok, mindenképpen kód módban másold ide, hogy az indentálás látszodjon (itt fenn a <> jel).

**Comment by kemendib** [comment]
Szoval:

Copy-paste-elve azt, amit a lovelace mintahoz irtatok, egy manualis
jartyara, ezt kapom:

ButtonCardJSTemplateError: TypeError: Cannot read property 'state' of
undefined in 'var met_level = states['sensor.met_alerts'].state; if (
met_level == 0 ) { return "green"; ...'
tap_action:
  action: more-info
type: custom:button-card
group_expand: false
hold_action:
  action: none
double_tap_action:
  action: none
layout: vertical
size: 30px
color_type: icon
show_name: false
show_state: false
show_icon: true
show_units: true
show_label: true
show_entity_picture: false
show_live_stream: false
card_size: 3
styles:
  label:
    - font-size: 90%
  card:
    - height: 80px
  icon:
    - color: |
        [[[
          var met_level = states['sensor.met_alerts'].state;
          if ( met_level == 0 ) {
            return "green";
          } else if ( met_level == 1 ) {
            return "var(--paper-item-icon-active-color)";
          } else if ( met_level == 2 ) {
            return "orange";
          } else if ( met_level == 3 ) {
            return "red";
          }
          return "black";
        ]]]
label: |
  [[[
    var met_alert =
states['sensor.met_alerts'].attributes.dominant_met_alert;
    return met_alert;
  ]]]
entity: sensor.met_alerts
default_color: var(--primary-text-color)
color_off: var(--paper-item-icon-color)
color_on: var(--paper-item-icon-active-color)
lock:
  enabled: false
  duration: 5
  unlock: tap

Atticus Maximus ***@***.***> ezt írta (időpont: 2021. jún.
21., H 18:08):

**Comment by amaximus** [comment]
Mi a neve a szenzornak? (Developer Tools -> States -> keress arra pl., hogy met.hu)

**Comment by kemendib** [comment]
Obasszus, sensor.met_riasztas, nem pedig alert, mint a mintaban... Ez kesz
a megoldas... Teszek egy probat...

Atticus Maximus ***@***.***> ezt írta (időpont: 2021. jún.
21., H 18:24):

**Comment by kemendib** [comment]
Igen, igy megy. Viszont csak egy riasztast ir ki. Most ketto lenne itt, egy
egyes tipusu (zivatar), es egy kettes (a hoseg). Meg kehet azt oldani, hogy
mindkettot mutassa?

Balázs Kemendi ***@***.***> ezt írta (időpont: 2021. jún. 21., H
18:51):

**Comment by amaximus** [comment]
A legújabb verziónál a Readme végén találsz példát arra hogyan lehet az összes riasztást megjeleníteni.

**Comment by kemendib** [comment]
Koszonom szepen a segitseget! :)

Atticus Maximus ***@***.***> ezt írta (időpont: 2021. jún.
21., H 20:38):
