### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/met_alerts_hu#2]
Is `dominant_met_alert_value` attribute and the main state of the sensor the same?
Currently they reflect the same number, will it always be like this? It's important to know which is worth better to be used in automations.

Note: please enable Discussions for your repos so we can put questions like this without opening issues.

**Comment by amaximus** [comment]
Yes, both values are the same.

Discussions enabled.

**Comment by nagyrobi** [comment]
Thank you.
